### ISSUE TITLE
"No input at point" 

### ISSUE THREAD

**Issue by ewolf** [helpshift/emacs-up#9]
Thanks for putting this together, this looks fantastic for development. 

I just did a fresh install today, both of emacs to 27.2 and emacs-up.
I fire up cider via cider-jack-in and decide to do a little test

`clojure-hello.core> (+ 1 2)`

When I hit enter, all I get is the following in the message area of emacs 
`No input at point`

This occurs when I launch emacs  `emacs --no-window-system` or just `emacs` .

I know this is probably an artifact of one of the libraries, probably cider. Not sure even how to track this one down.

**Comment by vedang** [comment]
The problem is that the configuration in `emacs-up` expects the `point` in `cider-repl` to be on the newline. 

That is, 
`clojure-hello.core> (+ 1 2)` will give you `no input at point` error, but

```
clojure-hello.core> 
(+ 1 2)
```

will not.  Writing forms on the new line is a preference for us, but if you don't like it, you can turn it off. To do this, comment out https://github.com/helpshift/emacs-up/blob/0f3c49e582bf72e3eb63f87eb29d2515ef903eb9/hs-clj-packages.el#L60 in your configuration and restart.
